# CURRENTLY SENDS 1 EMAIL EVERY 3 SECONDS (BUT MORE ROBUST AND RELIABLE)

import mysql.connector
import smtplib
import time
import random
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from datetime import datetime, timedelta, timezone
from urllib.parse import quote

SMTP_SERVER = 'smtp.hostinger.com'
SMTP_PORT = 587
SMTP_USERNAME = 'careers@visionastraa.in'
SMTP_PASSWORD = '1?Q#v!$adw:M'

CAMPAIGN_ID = "ev_webinar_2025_07_03"

EMAIL_SUBJECT = "Job Opportunities in the EV Industry Webinar - July 03, 10:30 AM (Thu)"

EMAIL_BODY_TEMPLATE = """\
<html>
  <body style="font-family:Arial, sans-serif;line-height:1.5;color:#333;">
    <p>Dear {first_name},</p>
    <p>
      Sharing webinar link for <strong>"Job Opportunities in EV Industry"</strong> for <strong>2025 graduates</strong><br>
      (B.Tech & M.Tech) from <strong>EEE, ECE & Mechanical Engineering</strong> branches only.
    </p>
    <p><strong>Date: July 03, Thu</strong></p>
    <p><strong>Time: 10:30 AM, IST</strong></p>
    <p>
      Webinar Link: <a href="https://visionastraa.com/track/click.php?email={email}&target={meet_url}&campaign_id={campaign_id}" 
      target="_blank" style="color:#1a73e8;">Join Webinar</a>
    </p>
    <p><strong>Webinar Details (Virtual):</strong></p>
    <ul>
      <li>Fireside Chat with Special Guest:<br>
          Rahul Plavullathil, Head of Driveline, FPT Industrial, Turin, Italy (20 min)
      </li>
      <li>Moderated by:<br>
          Yedu Jathavedan, Co-founder & Chairman, VisionAstraa Group
      </li>
      <li>Conversation will cover:
        <ul>
          <li>Why EV?</li>
          <li>Industry Trends</li>
          <li>Job Opportunities in the EV Industry, etc.</li>
        </ul>
      </li>
    </ul>
    <p><strong>To add the webinar to your calendar and receive a reminder, please click "YES" on the calendar invite.</strong></p>
    <p>Best Regards,<br>VisionAstraa Group</p>
    <br>
    <p style="font-size:12px;color:#888;">
      If you no longer wish to receive emails from us, you can 
      <a href="https://visionastraa.com/track/unsubscribe.php?email={email}&campaign_id={campaign_id}" style="color:#1a73e8;">unsubscribe here</a>.
    </p>
    <img src="{image_url}" width="1" height="1" style="display:none;" />
  </body>
</html>
"""

def create_ics():
    dt_start = datetime(2025, 7, 3, 10, 30)
    dt_end = dt_start + timedelta(minutes=60)
    dtstamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    dtstart = dt_start.strftime("%Y%m%dT%H%M%S")
    dtend = dt_end.strftime("%Y%m%dT%H%M%S")
    return f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//VisionAstraa//EV Webinar//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTAMP:{dtstamp}
DTSTART;TZID=Asia/Kolkata:{dtstart}
DTEND;TZID=Asia/Kolkata:{dtend}
SUMMARY:Job Opportunities in EV Industry Webinar
UID:visionastraa-ev-webinar-20250703@visionastraa.in
ORGANIZER;CN=VisionAstraa Group:mailto:{SMTP_USERNAME}
DESCRIPTION:Join the webinar on Job Opportunities in EV Industry.\\nhttps://meet.google.com/prn-gckz-eug
LOCATION:Online (Google Meet)
STATUS:CONFIRMED
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR
"""

def send_email(to_address, first_name):
    meet_url = quote("https://meet.google.com/prn-gckz-eug", safe='')
    random_token = random.randint(100000, 999999)
    image_url = f"https://visionastraa.com/track/open.php?email={quote(to_address)}&campaign_id={CAMPAIGN_ID}&r={random_token}"

    body = EMAIL_BODY_TEMPLATE.format(
        first_name=first_name,
        email=quote(to_address),
        meet_url=meet_url,
        campaign_id=CAMPAIGN_ID,
        image_url=image_url
    )

    ics_content = create_ics()

    msg = MIMEMultipart('mixed')
    msg['Subject'] = EMAIL_SUBJECT
    msg['From'] = SMTP_USERNAME
    msg['To'] = to_address
    msg.attach(MIMEText(body, 'html'))

    ical = MIMEApplication(ics_content, _subtype='ics')
    ical.add_header('Content-Disposition', 'attachment; filename="invite.ics"')
    ical.add_header('Content-Class', 'urn:content-classes:calendarmessage')
    ical.add_header('Content-ID', 'calendar_message')
    msg.attach(ical)

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SMTP_USERNAME, to_address, msg.as_string())
        return True
    except Exception as e:
        print(f"❌ Error sending to {to_address}: {e}")
        return False

conn = mysql.connector.connect(
    host='srv1640.hstgr.io',
    user='u707137586_Campus_Hiring',
    password='6q+SFd~o[go',
    database='u707137586_Campus_Hiring'
)
cursor = conn.cursor(dictionary=True)

# tables = ['test']
tables = ['crdf25', 'crdf25_north', 'crdf25_south']

target_colleges = [
    "BAPUJI INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "DAYANANDA SAGAR COLLEGE OF ENGINEERING",
    "K.L.E.INSTITUTE OF TECHNOLOGY",
    "ATME COLLEGE OF ENGINEERING",
    "DAYANANDA SAGAR UNIVERSITY",
    "GOVERNMENT ENGINEERING COLLEGE",
    "RAJARAJESWARI COLLEGE OF ENGINEERING",
    "NAVKIS COLLEGE OF ENGINEERING, HASSAN",
    "SAHYADRI COLLEGE OF ENGINEERING & MANAGEMENT",
    "ATRIA INSTITUTE OF TECHNOLOGY",
    "S. S. E. T'S S. G. BALEKUNDRI INSTITUTE OF TECHNOLOGY",
    "CAMBRIDGE INSTITUTE OF TECHNOLOGY NORTH CAMPUS",
    "GHOUSIA COLLEGE OF ENGINEERING",
    "R.L.JALAPPA INSTITUTE OF TECHNOLOGY",
    "CHANNABASAVESHWARA INSTITUTE OF TECHNOLOGY",
    "JAIN COLLEGE OF ENGINEERING",
    "EAST POINT COLLEGE OF ENGINEERING & TECHNOLOGY",
    "RV INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
    "RAJIV GANDHI INSTITUTE OF TECHNOLOGY",
    "GOPALAN COLLEGE OF ENGINEERING AND MANAGEMENT",
    "SRI JAYACHAMARAJENDRA COLLEGE OF ENGINEERING",
    "SRINIVAS INSTITUTE OF TECHNOLOGY",
    "K.N.S. INSTITUTE OF TECHNOLOGY, BANGALORE-64",
    "ANJUMAN INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
    "BRINDAVAN COLLEGE OF ENGINEERING",
    "CHRIST DEEMED TO BE UNIVERSITY KENGERI CAMPUS",
    "G MADEGOWDA INSTITUTE OF TECHNOLOGY (GMIT)",
    "GOVERNMENT 5. K. 5. J. T. INSTITUTE",
    "AMRITA VISHWA VIDYAPEETHAM BENGALURU CAMPUS",
    "DR. AMBEDKAR INSTITUTE OF TECHNOLOGY",
    "KLE DR. M. S. SHESHGIRI COLLEGE OF ENGINEERING AND TECHNOLOGY, BELGAUM",
    "A P S COLLEGE OF ENGINEERING",
    "AMRUTA INSTITUTE OF ENGINEERING AND MANAGEMENT SCIENCES",
    "UNIVERSITY OF VISVESVARAYA COLLEGE OF ENGINEERING",
    "MALNAD COLLEGE OF ENGINEERING",
    "MARATHA MANDAL'S ENGINEERING COLLEGE, BELGAUM",
    "T JOHN INSTITUTE OF TECHNOLOGY",
    "JAIN DEEMED TO BE UNIVERSITY FACULTY OF ENGINEERING AND TECHNOLOGY",
    "JYOTHY INSTITUTE OF TECHNOLOGY",
    "UNIVERSITY B D T COLLEGE OF ENGINEERING",
    "BANGALORE COLLEGE OF ENGINEERING & TECHNOLOGY",
    "JAIN COLLEGE OF ENGINEERING & TECHNOLOGY",
    "KLE TECHNOLOGICAL UNIVERSITY",
    "KLE'S KLE COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "P.A.COLLEGE OF ENGINEERING",
    "RAJEEV INSTITUTE OF TECHNOLOGY",
    "SAMBHRAM INSTITUTE OF TECHNOLOGY",
    "UNIVERSITY OF MYSORE",
    "ACHARYA INSTITUTE OF TECHNOLOGY",
    "C.BYREGOWDA INSTITUTE OF TECHNOLOGY",
    "DON BOSCO INSTITUTE OF TECHNOLOGY",
    "EAST WEST COLLEGE OF ENGINEERING",
    "GOVT. ENGINEERING COLLEGE, HASSAN",
    "GSSS INSTITUTE OF ENGINEERING & TECHNOLOGY FOR WOMEN",
    "PROUDHADEVARAYA INSTITUTE OF TECHNOLOGY",
    "SJB INSTITUTE OF TECHNOLOGY",
    "ADICHUNCHANAGIRI INSTITUTE OF TECHNOLOGY, RAICHUR",
    "B.L.D.E.A'S V.P DR P.G.HALAKATTI COLLEGE OF ENGG. & TECH., BIJAPUR-03",
    "BALLARI INSTITUTE OF TECHNOLOGY & MANAGEMENT",
    "BHARATESH INSTITUTE OF TECHNOLOGY",
    "BMS INSTITUTE OF TECHNOLOGY & MANAGEMENT",
    "CAUVERY INSTITUTE OF TECHNOLOGY",
    "CMR INSTITUTE OF TECHNOLOGY",
    "DR. T.THIMMAIAH INSTITUTE OF TECHNOLOGY",
    "INANAVIKAS INSTITUTE OF TECHNOLOGY",
    "JAIN COLLEGE OF ENGINEERING AND RESEARCH",
    "JAIN INSTITUTE OF TECHNOLOGY",
    "K.S. SCHOOL OF ENGINEERING AND MANAGEMENT",
    "K.S.INSTITUTE OF TECHNOLOGY",
    "LINGARAJAPPA ENGINEERING COLLEGE",
    "M. S. RAMAIAH UNIVERSITY OF APPLIED SCIENCES",
    "MOODLAKATTE INSTITUTE OF TECHNOLOGY",
    "NITTE MEENAKSHI INSTITUTE OF TECHNOLOGY",
    "PRESIDENCY UNIVERSITY",
    "R.T.E.SOCIETY'S, RURAL ENGINEERING COLLEGE, HULKOTI",
    "SMT. KAMALA AND SRI VENKAPPA M AGADI COLLEGE OF ENGINEERING & TECHNOLOGY",
    "SRINIVAS UNIVERSITY INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "VEMANA INSTITUTE OF TECHNOLOGY",
    "VIDYA VIKAS INSTITUTE OF ENGINEERING & TECHNOLOGY",
    "VISVESVARAYA TECHNOLOGICAL UNIVERSITY CENTRE FOR POST GRADUATE STUDIES MUDDENAHALLI",
    "VIVEKANANDA INSTITUTE OF TECHNOLOGY",
    "AC COLLEGE OF ENGINEERING",
    "ADI SHANKARA INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "AHALIA SCHOOL OF ENGINEERING & TECHNOLOGY",
    "AL AZHAR COLLEGE OF ENGINEERING AND POLYTECHNIC",
    "ALBERTIAN INSTITUTE OF SCIENCE AND TECHNOLOGY (AISAT)-TECHNICAL CAMPUS",
    "AMAL JYOTHI COLLEGE OF ENGINEERING",
    "AMRITA VISHWA VIDYAPEETHAM AMRITAPURI CAMPUS",
    "AWH ENGINEERING COLLEGE",
    "BASELIOS MATHEWS II COLLEGE OF ENGINEERING",
    "BISHOP JEROME INSTITUTE",
    "CARMEL COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "CHINMAYA VISHWAVIDYAPEETH",
    "CHRIST KNOWLEDGE CITY",
    "COCHIN UNIVERSITY COLLEGE OF ENGINEERING KUTTANADU & COCHIN UNIVERSITY",
    "COCHIN UNIVERSITY OF SCIENCE AND TECHNOLOGY",
    "COLLEGE OF DENGINEERING KIDANGOOR",
    "COLLEGE OF ENGINEERING ADOOR",
    "COLLEGE OF ENGINEERING AND MANAGEMENT PUNNAPRA",
    "COLLEGE OF ENGINEERING KALLOOPPARA",
    "COLLEGE OF ENGINEERING KARUNAGAPPALLY",
    "COLLEGE OF ENGINEERING MUNNAR",
    "COLLEGE OF ENGINEERING MUTTATHARA",
    "COLLEGE OF ENGINEERING PERUMON",
    "COLLEGE OF ENGINEERING TRIKARIPUR",
    "COLLEGE OF ENGINEERING TRIVANDRUM",
    "COLLEGE OF ENGINEERING, ARANMULA",
    "COLLEGE OF ENGINEERING, CHERTHALA",
    "COLLEGE OF ENGINEERING, KOTTARAKKARA",
    "COLLEGE OF ENGINEERING, THALASSERY",
    "COLLEGE OF ENGINEERING, VADAKARA",
    "DEPARTMENT OF POLYMER SCIENCE AND RUBBER TECHNOLOGY, COCHIN UNIVERSI",
    "DEPARTMENT OF SHIP TECHNOLOGY, COCHIN UNIVERSITY OF SCIENCE AND TECHNO",
    "ERANAD KNOWLEDGECITY TECHNICAL CAMPUS",
    "FEDERAL INSTITUTE OF SCIENCE AND TECHNOLOGY (FISAT)",
    "GOVERNMENT COLLEGE OF ENGINEERING KANNUR",
    "GOVERNMENT COLLEGE OF ENGINEERING, WAYANAD",
    "GOVERNMENT ENGINEERING COLLEGE IDUKKI",
    "GOVERNMENT ENGINEERING COLLEGE SREEKRISHNAPURAM",
    "GOVERNMENTENGINEERINGCOLLEGETHRISSUR",
    "GOVT. ENGINEERING COLLEGE, KOZHIKODE",
    "GREGORIAN INSTITUTE OF TECHNOLOGY",
    "HEERA COLLEGE OF ENGINEERING AND TECHNOLOGY (HCET)",
    "HOLY GRACE ACADEMY OF ENGINEERING",
    "ICCS COLLEGE OF ENGINEERING AND MANAGEMENT",
    "IES COLLEGE OF ENGINEERING",
    "ILAHIA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "INDIRA GANDHI INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "JAIBHARATH COLLEGE OF MANAGEMENT & ENGINEERING TECHNOLOGY",
    "JAIN DEEMED TO BE UNIVERSITY OFF CAMPUS KOCHI",
    "JAWAHARLAL COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "JOHN COX MEMORIAL CSI INSTITUTE OF TECHNOLOGY",
    "JYOTHI ENGINEERING COLLEGE",
    "KELAPPAJI COLLEGE OF AGRICULTURAL ENGINEERING & TECHNOLOGY, TAVANUR",
    "KM COLLEGE OF ENGINEERING",
    "KMCT COLLEGE OF ENGINEERING FOR WOMEN",
    "KMCT INSTITUTE OF EMERGING TECHNOLOGY AND MANAGEMENT",
    "KMEA ENGINEERING COLLEGE",
    "KOTTAYAM INSTITUTE OF TECHNOLOGY AND SCIENCE",
    "KVM COLLEGE OF ENGINEERING & IT",
    "LAYOLA INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "LBS COLLEGE OF ENGINEERING",
    "LBS INSTITUTE OF TECHNOLOGY FOR WOMEN",
    "LOURDES MATHA COLLEGE OF SCIENCE AND TECHNOLOGY",
    "M. DASAN INSTITUTE OF TECHNOLOGY",
    "MAHAGURU INSTITUTE OF TECHNOLOGY",
    "MALABAR COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "MALABAR INSTITUTE OF TECHNOLOGY",
    "MANGALAM COLLEGE OF ENGINEERING",
    "MAR ATHANASIUS COLLEGE OF ENGINEERING, KOTHAMANGALAM",
    "MAR BASELIOS CHRISTIAN COLLEGE OF ENGINEERING & TECHNOLOGY",
    "MAR BASELIOS COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "MARIAN ENGINEERING COLLEGE",
    "MEA ENGINEERING COLLEGE, PERINTHALMANNA",
    "MENTOR ACADEMY FOR DESIGN ENTREPRENEURSHIP INNOVATION AND TECHNOLOGY",
    "MES COLLEGE OF ENGINEERING & TECHNOLOGY",
    "MES INSTITUTE OF TECHNOLOGY & MANAGEMENT",
    "MET'S SCHOOL OF ENGINEERING, MALA",
    "MG COLLEGE OF ENGINEERING",
    "MGM TECHNOLOGICAL CAMPUS",
    "MODEL ENGINEERING COLLEGE",
    "MOHANDAS COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "MOUNT ZION COLLEGE OF ENGINEERING",
    "MOUNT ZION INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "MUSALIAR COLLEGE OF ENGINEERING AND TECHNOLOGY PATHANAMTHITTA",
    "MUSALIAR COLLEGE OF ENGINEERING",
    "MUSLIM ASSOCIATION COLLEGE OF ENGINEERING",
    "MUTHOOT INSTITUTE OF TECHNOLOGY AND SCIENCE",
    "NEHRU COLLEGE OF ENGINEERING AND RESEARCH CENTRE",
    "NSS COLLEGE OF ENGINEERING",
    "P.A.AZIZ COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "PROVIDENCE COLLEGE OF ENGINEERING",
    "RAJADHANI INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "RAJADHANI INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "RAJAGIRI SCHOOL OF ENGINEERING & TECHNOLOGY",
    "RAJIV GANDHI INSTITUTE OF TECHNOLOGY, KOTTAYAM",
    "ROYAL COLLEGE OF ENGINEERING & TECHNOLOGY",
    "SAHRDAYA COLLEGE OF ENGINEERING & TECHNOLOGY",
    "SAINTS COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "SARABHAI INSTITUTE OF SCIENCE AND TECHNOLOGY",
    "SCHOOL OF OCEAN ENGINEERING AND UNDERWATER TECHNOLOGY",
    "SCMS SCHOOL OF ENGINEERING & TECHNOLOGY",
    "SNGIST GROUP OF INSTITUTIONS",
    "SNM INSTITUTE OF MANAGEMENT AND TECHNOLOGY",
    "SREE BUDDHA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "SREE CHITRA THIRUNAL COLLEGE OF ENGINEERING",
    "SREE NARAYANA GURU COLLEGE OF ENGINEERING & TECHNOLOGY",
    "SREE NARAYANA GURUKULAM COLLEGE OF ENGINEERING",
    "SREE NARAYANA INSTITUTE OF TECHNOLOGY",
    "SREEPATHY INSTITUTE OF MANAGEMENT AND TECHNOLOGY",
    "ST THOMAS INSTITUTE FOR SCIENCE AND TECHNOLOGY",
    "ST. JOSEPH'S COLLEGE OF ENGINEERING & TECHNOLOGY, PALAI",
    "ST. THOMAS COLLEGE OF ENGINEERING & TECHNOLOGY",
    "ST.THOMAS COLLEGE OF ENGINEERING & TECHNOLOGY",
    "T.K.M INSTITUTE OF TECHNOLOGY",
    "THEJUS ENGINEERING COLLEGE",
    "TKM COLLEGE OF ENGINEERING",
    "TOCH INSTITUTE OF SCIENCE & TECHNOLOGY",
    "TOMS COLLEGE OF ENGINEERING",
    "TRAVANCORE ENGINEERING COLLEGE, OYOOR",
    "TRINITY COLLEGE OF ENGINEERING",
    "UNIVERSAL ENGINEERING COLLEGE",
    "UNIVERSITY COLLEGE OF ENGINEERING",
    "UNIVERSITY COLLEGE OF ENGINEERING.",
    "VALIA KOONAMBAIKULATHAMMA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    "VERGHESE KURIEN INSTITUTE OF DAIRY AND FOOD TECHNOLOGY",
    "VIDYA ACADEMY OF SCIENCE AND TECHNOLOGY TECHNICAL CAMPUS",
    "VIMAL JYOTHI ENGINEERING COLLEGE",
    "VISAT ENGINEERING COLLEGE",
    "YOUNUS COLLEGE OF ENGINEERING AND TECHNOLOGY",
]

college_placeholders = ', '.join(['%s'] * len(target_colleges))

for tbl in tables:
    query = f"""
        SELECT email, first_name FROM {tbl} 
WHERE college IN ({college_placeholders}) 
AND emailSent = 0 
AND email NOT IN (SELECT email FROM unsubscribed_emails)
    """

    cursor.execute(query, target_colleges + [CAMPAIGN_ID])

    for row in cursor.fetchall():
        if send_email(row['email'], row['first_name']):
            print(f"✅ Sent to {row['email']}")
            cursor.execute(f"UPDATE {tbl} SET emailSent=1 WHERE email=%s", (row['email'],))
            conn.commit()

cursor.close()
conn.close()
